"""Initial schema

Revision ID: eaf70ffb1a1c
Revises: 
Create Date: 2026-09-02 11:24:18.283106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf70ffb1a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('auto_resolved_count', sa.Integer(), nullable=False),
    sa.Column('escalated_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unresolved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('processing_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('transaction_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metrics_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=50), nullable=True),
    sa.Column('refund_id', sa.String(length=50), nullable=True),
    sa.Column('settlement_id', sa.String(length=50), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_approved_by', sa.String(length=100), nullable=True),
    sa.Column('human_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('order_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=50), nullable=True),
    sa.Column('settlement_id', sa.String(length=50), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exception_id', sa.String(length=50), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('tool_used', sa.String(length=100), nullable=True),
    sa.Column('input_ref', sa.String(length=200), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_action', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exception_id', sa.String(length=50), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=False),
    sa.Column('deterministic_confidence', sa.Float(), nullable=False),
    sa.Column('evidence_completeness', sa.Float(), nullable=False),
    sa.Column('source_consistency', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=30), nullable=True),
    sa.Column('auto_resolve', sa.Boolean(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('payment_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigation_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('source_table', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('refund_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('settlement_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payout_reference', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    op.drop_table('refunds')
    op.drop_table('investigation_evidence')
    op.drop_table('payments')
    op.drop_table('investigations')
    op.drop_table('audit_events')
    op.drop_table('reconciliation_matches')
    op.drop_table('orders')
    op.drop_table('exceptions')
    op.drop_table('evaluation_results')
    op.drop_table('bank_transactions')
    op.drop_table('reconciliation_runs')
    op.drop_table('merchants')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
